# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hEDcQLYXu8fU2FtPNdf3ZPkihGla4rBV
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load model
model = tf.keras.models.load_model("my_mobilenet_model(1).h5")

# Kelas (ubah sesuai dataset kamu)
class_names = ["Alternaria Leaf Spot", "Bacterial Spot Rot", "Black Rot","Cabbage Aphid Colony", "Downy Mildew","No Disease","Club Root","Ring Spot"]

st.title("🌿 Klasifikasi Penyakit Tanaman Menggunakan MobileNet")
st.write("Upload gambar daun untuk mengetahui hasil prediksi")

# Upload gambar
uploaded_file = st.file_uploader("Pilih gambar daun...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Gambar yang diupload", use_column_width=True)

    # Preprocessing gambar sesuai input MobileNet
    img = image.resize((224, 224))  # ukuran default MobileNetV2
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)

    # Prediksi
    prediction = model.predict(img_array)
    score = tf.nn.softmax(prediction[0])

    st.write("### Hasil Prediksi:")
    st.write(f"➡️ {class_names[np.argmax(score)]} ({100 * np.max(score):.2f}%)")